name: pureshift
channels:
  - defaults
dependencies:
  - pip=24.0
  - python=3.10.14
  - setuptools=69.5.1
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - numpy==1.24.3
      - nmrglue==0.10
      - matplotlib==3.8.4
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tf-keras==2.14.1
#prefix: /home/nmrbox/0005/vkakita/anaconda3/envs/tf
